version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/comments"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/events"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/moderation"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/posts"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/query"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
